server:
  port: 60000
spring: 
  application:
    name: iot-smart-city-device-client

mqtt: 
  server_uri: tcp://127.0.0.1:1883
  clear_session: true
  connection_timeout: 100
  auto_reconnect: true
  keep_alive: 20
  topic: /as/mqtt/status/counter/tempurature
  username: test
  password: test
  ipAddress: 127.0.0.1:1883
  deviceName: 温度计
  productKey: 计数传感器
  
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:8889/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: iot-smart-city-device-client
    prefer-ip-address: true     #访问路径可以显示IP地址     

info: 
  app.name: iot-smart-city-device-client
  company.name: www.smart_city.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$