server:
  port: 30003
spring: 
  application:
    name: iot-smart-city-service-message
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sc_message?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒） 
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mapper/**.xml

message: 
  maxResendTimes: 6   #消息最大重发次数  
  poolSize: 10      #消息任务线程池
  timeout: 6   #分钟
  pageSize: 100     #分页查询每次查询条数
  
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:8889/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: iot-smart-city-service-message
    prefer-ip-address: true     #访问路径可以显示IP地址     

info: 
  app.name: iot-smart-city-service-message
  company.name: www.xuecheng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$